name: "Nitro MCP Publish"
description: "Publishes MCP feature collections to the Nitro registry"
author: "ChilliCream"
branding:
  icon: "upload-cloud"
  color: "red"

inputs:
  tag:
    description: "The tag of the MCP feature collection version"
    required: true
  stage:
    description: "The name of the stage"
    required: true
  mcp-feature-collection-id:
    description: "The ID of the MCP Feature Collection"
    required: true
  api-key:
    description: "API key for authentication"
    required: true
    secret: true
  force:
    description: "Continue publishing even if breaking changes or validation errors are detected."
    required: false
    default: "false"
  wait-for-approval:
    description: "Require approval in the Nitro UI to continue publishing when breaking changes or validation errors are detected."
    required: false
    default: "false"
  cloud-url:
    description: "The URL of the Nitro registry"
    required: false
  job-id:
    description: "The ID of the current job"
    required: false
    default: ${{ job.check_run_id }}

runs:
  using: "node20"
  main: "dist/index.js"
